apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-registration-config
  namespace: patient-registration
data:
  SPRING_PROFILES_ACTIVE: "prod"
  # Add any other environment-specific configuration here
  # Example:
  # DATABASE_URL: "jdbc:postgresql://db-host:5432/patientdb"
  # SPRING_DATASOURCE_USERNAME: "dbuser"
  # SPRING_DATASOURCE_PASSWORD: "dbpassword"
